export enum ApiRoutes{
    CALCULATIONS = '/api/calculations',
    EMAILS = '/api/emails',
    LINES = '/api/lines',
    PROPERTIES = '/api/material-properties',
    SKILLETS = '/api/skillets',
    CORES = '/api/cores',
    PERIODS = '/api/periods',
    RECIPIENTS = '/api/email-recipients',
    ADMINS = '/api/admins',
    PRICETIERS = '/api/price-tiers',
    UMKARTONSPRICETIERS = '/api/umkartons-price-tiers',
    UMKARTONS = '/api/umkartons',
    DECKELS = '/api/deckels',
    EMAILTEXT = '/api/email-text',
}